--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app.kubernetes.io/name: postgres
  spec: 
    containers: 
      - 
        env: 
          - 
            name: POSTGRES_DB
            valueFrom: 
              configMapKeyRef: 
                key: dbname
                name: db
          - 
            name: POSTGRES_USER
            valueFrom: 
              configMapKeyRef: 
                key: username
                name: db
          - 
            name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef: 
                key: dbpwd
                name: mysecrets
        image: "postgres:latest"
        name: postgres
        ports: 
          - 
            containerPort: 5432
        volumeMounts: 
          - 
            mountPath: /var/lib/postgresql/data
            name: mendix-pgdata
    volumes: 
      - 
        hostPath: 
          path: /home/docker/pgdata
        name: mendix-pgdata
  template: 
    metadata: 
      labels: 
        app.kubernetes.io/name: postgres
