apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
  labels:
    app: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: springbootpostgres:0.0.1
        ports:
        - containerPort: 8080
        env: 
          - 
            name: POSTGRES_DB
            valueFrom: 
              configMapKeyRef: 
                key: dbname
                name: db
          - 
            name: POSTGRES_USER
            valueFrom: 
              configMapKeyRef: 
                key: username
                name: db
          - 
            name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef: 
                key: dbpwd
                name: mysecrets
          - 
            name: POSTGRES_DB_SVC
            valueFrom: 
              configMapKeyRef: 
                key: dbsvc
                name: db
