---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "mysql-secret"
  namespace: "default"
  labels:
    app: "mysql"
data:
  ##this is base64 
  MYSQL_PASSWORD: "cm9vdA=="

---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "mysql-config"
  namespace: "default"
  labels:
    app: "mysql"
data:
  MYSQL_USER: "root"
  MYSQL_DATABASE: "test"
  
  
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "mysql"
  namespace: "default"
  labels:
    app: "mysql"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "mysql"
  template:
    metadata:
      labels:
        app: "mysql"
    spec:
      containers:
      - name: "mysql"
        image: "mysql"
        ports: 
        - containerPort: 3306
        env:
        - name: "MYSQL_USER"
          valueFrom:
            configMapKeyRef:
              key: "MYSQL_USER"
              name: "mysql-config"
        - name: "MYSQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "MYSQL_PASSWORD"
              name: "mysql-secret"
         - name: "MYSQL_ROOT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "MYSQL_PASSWORD"
              name: "mysql-secret"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "mysq;-hpa-nk7r"
  namespace: "default"
  labels:
    app: "mysql"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "mysql"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
