---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "postgres1-service"
  namespace: "default"
  labels:
    app: "postgres1"
spec:
  ports:
  - name: "postgres1db"
    protocol: "TCP"
    port: 5432
    targetPort: 5432
  - name: "postgres1db"
    protocol: "TCP"  
    port: 5431
    targetPort: 5431
  selector:
    app: "postgres1"
  type: "LoadBalancer"
  loadBalancerIP: ""
